apiVersion: v1
kind: Pod
metadata:
  name: kafka2db
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: kafka2db
      image: cvrnogueira/kafka2db:1.4
      command:
        - sh
        - /opt/flink-upload.sh