apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather2kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather2kafka
  template:
    metadata:
      labels:
        app: weather2kafka
    spec:
      restartPolicy: Always
      containers:
        - name: weather2kafka-container
          image: cvrnogueira/weather2kafka:1.0
          env:
            - name: KAFKA_CLUSTER_ENTRY_POINT
              value: ${KAFKA_CLUSTER_ENTRY_POINT}
